name = "QuantumNaturalGradient"
uuid = "8d03283f-5cc1-4355-9ceb-601ddb1c7e78"
authors = ["Daniel Alcalde <d.alcalde.puente@fz-juelich.de>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributed = "8ba89e20-285c-5b6f-9357-94700520ee1b"
ITensors = "9136182c-28ba-11e9-034c-db9fb085ebd5"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
LogExpFunctions = "2ab3a3ac-af41-5b50-aa03-7779005ae688"
ParallelDataTransfer = "2dcacdae-9679-587a-88bb-8b444fb7085b"
ParallelGradient = "2abb11c0-4451-46e5-9056-fbb582a36d1b"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PastaQ = "30b07047-aa8b-4c78-a4e8-24d720215c19"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
RandomizedLinAlg = "0448d7d9-159c-5637-8537-fd72090fea46"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
TimerOutputs = "a759f4b9-e2f1-59dc-863e-4aeb61b1ea8f"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
